### ISSUE TITLE
Multiplying by 2 when concatenate the mix feature?

### ISSUE THREAD

**Issue by anthonytmh** [Megvii-Nanjing/BBN#15]
Thank you for your interesting works. Would you mind explaining the purpose of multiplying the mixed feature by 2 after concatenating them? Thanks.
https://github.com/Megvii-Nanjing/BBN/blob/7992e908842f5934f0d1ee3f430d796621e81975/lib/core/combiner.py#L56

**Comment by nisargshah1999** [comment]
Hi could you explain this..

Thanks
