### ISSUE TITLE
About the implementation of in the cumulative learning stage

### ISSUE THREAD

**Issue by YTEP-ZHI** [Megvii-Nanjing/BBN#25]
I'm confused about the implementation of fusing features from two branches. In the combiner.py of your code, it seems that features from two branchs are mixed by concatenating. (Related codes are as follows)
```
        mixed_feature = 2 * torch.cat((l * feature_a, (1-l) * feature_b), dim=1)
        output = model(mixed_feature, classifier_flag=True)
        loss = l * criterion(output, label_a) + (1 - l) * criterion(output, label_b)
```

However, in the section 4.1 of your paper, it's said that the two features are integrated by element-wise addition. 
![image](https://user-images.githubusercontent.com/48089846/114258069-9d993480-99f6-11eb-95a3-47d17c77e7cd.png)

Is the feature fusing conducted by concatenating or element-wise addition? Or am I misunderstanding anything?(Correct me if I'm wrong) Looking forward to your reply.

**Comment by wangzhl1999** [comment]
The article and code are consistent, and the two classifiers are combined into one classifier in the code.

**Comment by YTEP-ZHI** [comment]
How time flies. It was posted almost three years ago.
