### ISSUE TITLE
question about loss curve at inaturalist2019

### ISSUE THREAD

**Issue by Haijunlv** [Megvii-Nanjing/BBN#3]
hi, i just use bbn to train in inaturalist2019, the config is same as config of iNaturalist2018.yaml.
thanks to the clean code, it is very easy to get good result with resnet50 baseline 2x.
But i found loss curve is very strage.
train loss at 67 epoch got highest.
Have you gotten the same curve? Could you explain the reason? 

![image](https://user-images.githubusercontent.com/28926237/75972378-492ba780-5f0e-11ea-8740-4711736a11df.png)

**Comment by Haijunlv** [comment]
result on exapmle cifar10 also show same cure
![image](https://user-images.githubusercontent.com/28926237/76056675-35d21800-5fb2-11ea-86d1-98d9e8994d85.png)

**Comment by ZhouBoyan** [comment]
Yes, I have got the same curve as you.
Acctually, two branches take care of head class and tail class respectively, which indicates that the conventional branch tends to classify one picture as head class and the re-balancing branch as tail class. 
With the cumulative learning strategy, the learning focus gradually moves from the conventional branch to the re-balancing branch, leading to that the two branches conflicting with each other (e.g. epoch 60-80) . With the loss optimized, the conflicts gradually disappeared.
We advise you to split the combined fc (I combine them just for simplification) into two parts （one for conventional branch and the other for re-balancing branch）and observe their individual accuracy or loss.
